const menuList = [
    {
        title:'首页',
        key:'/admin/home'
    }, 
    {
        title:'UI',
        key:'/admin/UI',
        Children:[
            {
                title:'option1',
                key:'/admin/option1'
            },
            {
                title:'option2',
                key:'/admin/option2'
            },
            {
                title:'option3',
                key:'/admin/option3'
            }, 
            {
                title:'option4',
                key:'/admin/option4'
            }
        ]
    },
    {
        title:'图表',
        key:'/admin/tubiao',
        Children:[
            {
                title:'option1',
                key:'/admin/option1'
            },
            {
                title:'option2',
                key:'/admin/option2'
            },
            {
                title:'option3',
                key:'/admin/option3'
            }, 
            {
                title:'option4',
                key:'/admin/option4'
            }
        ]
    },
    {
        title:'anniu',
        key:'/admin/anniu',
        Children:[
            {
                title:'option1',
                key:'/admin/option1'
            },
            {
                title:'option2',
                key:'/admin/option2'
            },
            {
                title:'option3',
                key:'/admin/option3'
            }, 
            {
                title:'option4',
                key:'/admin/option4'
            }
        ]
    },
    {
        title:'设置',
        key:'/admin/shezhi'
    }
]
   
export default menuList